### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by george-i** [Drougnov/Appvila#1]
I found this theme on some websites, to be paid or with paid access to the website.  
I'm interested in using it, but you don't have a license mentioned yet.

**Comment by Drougnov** [comment]
> I found this theme on some websites, to be paid or with paid access to the website. I'm interested in using it, but you don't have a license mentioned yet.

Hello,

Thank you for bringing this to my attention. I can assure you that the theme used in this repository has been obtained legally from UIdeck and the license information is included in the license.txt file that you mentioned. I have also mentioned the origin of the theme in the project's footer and readme file.

Let me know if there is anything else I can help you with.

Best regards
Rocky

**Comment by george-i** [comment]
I was expecting to find the license information on the repository Readme file, not on a code file.
